Resources:
  ElastiCacheCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      AutoMinorVersionUpgrade: 'true'
      Engine: redis
      CacheNodeType: ${env:CACHE_INSTANCE_CLASS}
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - Fn::GetAtt: ElastiCacheVpcSecurityGroup.GroupId
      CacheSubnetGroupName:
        Ref: ElastiCacheSubnetGroup

  ElastiCacheSubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      Description: GraphQL ElastiCache subnet group
      SubnetIds:
        - ${env:SUBNET_ID_A}
        - ${env:SUBNET_ID_B}

  ElastiCacheVpcSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow Lambdas to access elasticache
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
      VpcId: ${env:VPC_ID}

  LambdaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for GraphQL Lambda functions'
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: -1
          FromPort: 0
          ToPort: 65535
      VpcId: ${env:VPC_ID}

  ApplicationRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      PermissionsBoundary:
        Fn::Join: [
          "", [
            "arn:aws:iam::",
            {
              "Ref": "AWS::AccountId"
            },
            ":policy/NGAPShRoleBoundary"
          ]
        ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBase
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticache:*
                Resource: '*'

# Output the following resources so that other stacks can access the values
Outputs:
  ElastiCacheEndpoint:
    Value:
      Fn::GetAtt:
        - ElastiCacheCluster
        - RedisEndpoint.Address
    Export:
      Name: ${self:provider.stage}-GraphQLElastiCacheEndpoint

  ElastiCachePort:
    Value:
      Fn::GetAtt:
        - ElastiCacheCluster
        - RedisEndpoint.Port
    Export:
      Name: ${self:provider.stage}-GraphQLElastiCachePort

  GraphQLLambdaSecurityGroup:
    Value:
      Ref: LambdaSecurityGroup
    Export:
      Name: ${self:provider.stage}-GraphQLLambdaSecurityGroup

  GraphQLElastiCacheVpcSecurityGroup:
    Value:
      Ref: ElastiCacheVpcSecurityGroup
    Export:
      Name: ${self:provider.stage}-GraphQLElastiCacheVpcSecurityGroup

  GraphQLApplicationRoleDev:
    Description: Role used to execute commands across the application
    Value:
      Fn::GetAtt:
        - ApplicationRole
        - Arn
    Export:
      Name: dev-GraphQLApplicationRole

  GraphQLApplicationRole:
    Description: Role used to execute commands across the application
    Value:
      Fn::GetAtt:
        - ApplicationRole
        - Arn
    Export:
      Name: ${self:provider.stage}-GraphQLApplicationRole

  CertificateLambdaLayer:
    Value:
      Ref: CertificateLambdaLayer
    Export:
      Name: ${self:provider.stage}-CertificateLambdaLayer
